package com.filip.nfcbak1;

/**
 * Created by Filip on 22.04.2017.
 */
public interface Constants {

    int NOT_LOGGED_IN_STATE = 1;
    int NOT_REGISTERED_STATE = 2;
    int REGISTERED_STATE = 3;

    long VALID_LOGIN_TIME = 30000; //24 hours = 86 400 000
 
    String STARTED_FROM_ACTIVITY = "STARTED_FROM_ACTIVITY";
    String RESTARTED_FROM_BROADCAST = "RESTARTED_FROM_BROADCAST";

    String REGISTRATION_SUCCESFUL = "REGISTRATION_SUCESSFUL";
    String AUTHENTICATION_SUCCESFUL = "AUTHENTICATION_SUCCESFUL";
    String NOTIFICATION_START = "NOTIFICATION_START";
    String LOGIN_TIMEOUT_START = "LOGIN_TIMEOUT_START";
}
